import { geoponto } from "../firebase";

export const hirer = {
  uid: "abc",
  atividade: "contratante",
  pessoais: {
    telefone: "+5511111111111",
    nome: "luis felipe spinola",
    genero: "masculino",
    nascimentoDDMMAAAA: "23091989",
    meioDeContatoPreferido: "whatsapp",
    cpf: "35593586802",
    email: "lfspinola@hotmail.com",
    foto: "somehttp",
  },
  enderecos: [
    {
      nome: "casa",
      logradouro: "rua orides gemente",
      numero: "650",
      complemento: "",
      bairro: "jardim oriental",
      cep: "18120000",
      cidade: "mairinque",
      estado: "sp",
      coordinates: [-23.5221066, -46.7041006],
      tipoDeHabitacao: "apartamento",
      numeroDeComodos: 5,
      numeroDeMoradores: 1,
    },
  ],
  coordinates: geoponto(-23.5221066, -46.7041006),
  senha: "Felipe@0",
  agendamentos: [
    {
      horaAgendada: "10",
      minAgendado: "00",
      diaAgendado: "ter",
      numeroDiariasEm4Semanas: 4,
      faxinar: true,
      lavar: false,
      passar: false,
      cozinhar: false,
      diarista: {
        nomeDiarista: "Maria Aparecida",
        celularDiarista: "22222222222",
      },
    },
    {
      horaAgendada: "10",
      minAgendado: "00",
      diaAgendado: "qui",
      numeroDiariasEm4Semanas: 4,
      diarista: {
        nomeDiarista: "Maria Aparecida",
        celularDiarista: "22222222222",
      },
      faxinar: true,
      lavar: false,
      passar: false,
      cozinhar: false,
    },
  ],
};

export const worker = {
  uid: "abc",
  atividade: "diarista",
  pessoais: {
    telefone: "+5522222222222",
    nome: "carla machado",
    genero: "feminino",
    nascimentoDDMMAAAA: "24051967",
    meioDeContatoPreferido: "whatsapp",
    cpf: "09908949837",
    email: "carla@hotmail.com",
    foto:
      "https://firebasestorage.googleapis.com/v0/b/nilda-6b3b8.appspot.com/o/fotoPerfil%2F6hbvmpioF3QJs1rjHaSUmUOvWTC2?alt=media&token=bba7439d-85cf-42d1-9b0e-d27f80c85d97",
  },
  enderecos: [
    {
      logradouro: "rua orides gemente",
      numero: "650",
      complemento: "",
      bairro: "jardim oriental",
      cep: "18120000",
      cidade: "mairinque",
      estado: "sp",
      coordinates: [-23.5221066, -46.7041006],
    },
  ],
  beneficios: {
    ferias: true,
    decT: true,
    planoSaude: true,
  },
  profissionais: {
    cnpj: "12345678910121",
    diasLivres: [true, true, true, true, true, false, false],
    diasOcup: [false, false, false, false, false, true, true],
    diasFolga: [false, false, false, false, false, false, false],
    faxinar: true,
    lavarRoupas: true,
    passarRoupas: true,
    cozinhar: true,
  },
  senha: "Carla@0",
  bancarios: {
    banco: "033",
    agencia: "7431",
    tipoDeConta: "corrente",
    conta: "1774037",
  },
  coordinates: geoponto(-23.5221066, -46.7041006),
};
