import { geoponto } from "../firebase";

export const hirer = {
  atividade: "contratante",
  coordinates: geoponto(-23.5560666, -46.65556249999999),
  cpf: "099.089.498-37",
  email: "marachelles@hotmail.com",
  bairro: "Pinheiros",
  cep: "00000000",
  cidade: "São Paulo",
  complemento: "",
  estado: "SP",
  foto:
    "https://firebasestorage.googleapis.com/v0/b/nilda-6b3b8.appspot.com/o/fotoPerfil%2F6hbvmpioF3QJs1rjHaSUmUOvWTC2?alt=media&token=bba7439d-85cf-42d1-9b0e-d27f80c85d97",
  logradouro: "Rua Peixoto Gomide",
  numero: "250",
  comodos: 1,
  moradores: 3,
  tipo: "apartamento",
  genero: "feminino",
  nascimentoDDMMAAAA: "24/05/1967",
  nome: "Maria Lúcia da Silva",
  telefone: "+55 (11) 996 508 820",
  senha: "Mara@0",
  uid: "AyDH6Q4P6RPap50R4nfNDDcl36r2",
};

export const worker = {
  atividade: "diarista",
  cnpj: "36.334.352/0001-20",
  cnpjVerificado: true,
  coordinates: geoponto(-23.5560501, -46.6555158),
  cpf: "099.089.498-37",
  decimoTerceiro: true,
  diasFolga: {
    seg: false,
    ter: false,
    qua: false,
    qui: false,
    sex: false,
    sab: false,
    dom: false,
  },
  diasLivres: {
    seg: true,
    ter: true,
    qua: false,
    qui: false,
    sex: false,
    sab: false,
    dom: false,
  },
  diasOcup: {
    seg: false,
    ter: false,
    qua: false,
    qui: false,
    sex: false,
    sab: false,
    dom: false,
  },
  verificador: {
    seg: true,
    ter: true,
    qua: false,
    qui: false,
    sex: false,
    sab: false,
    dom: false,
  },
  email: "marachelles@hotmail.com",
  foto:
    "https://firebasestorage.googleapis.com/v0/b/nilda-6b3b8.appspot.com/o/fotoPerfil%2FZC1R8NdLnlc6FGQlP6rbjlkVavM2?alt=media&token=d293f99b-e55c-4763-88f8-afdedcd55a89",
  bairro: "Pinheiros",
  cep: "00000000",
  cidade: "São Paulo",
  complemento: "",
  estado: "SP",
  logradouro: "Rua Peixoto Gomide",
  numero: "250",
  faxinar: true,
  ferias: true,
  genero: "feminino",
  lavarRoupas: false,
  nascimentoDDMMAAAA: "24/05/1967",
  nome: "Maria Lúcia da Silva",
  senha: "Mara@0",
  telefone: "+55 (11) 996 508 820",
  uid: "GkDH6Q4P6RPap50R4nfNDDcl36r2",
  banco: "Santander",
  agencia: "1831-1",
  tipoDeConta: "corrente",
  conta: 18140417,
};

export const services = [
  {
    sid: "E1hGLMco8eS7X0F6wwiF",
    horaAgendada: "10",
    minAgendado: "00",
    diaAgendado: "ter",
    numeroDiariasEm4Semanas: 4,
    faxinar: true,
    lavar: false,
    passar: false,
    cozinhar: false,
    nomeDiarista: "Maria Aparecida",
    telefoneDiarista: "+55 (22) 222 222 222",
    pagamento: {},
  },
  {
    sid: "QNVsl3yafT8LDRNhTpe7",
    horaAgendada: "10",
    minAgendado: "00",
    diaAgendado: "seg",
    numeroDiariasEm4Semanas: 4,
    nomeDiarista: "Maria Aparecida",
    telefoneDiarista: "+55 (22) 222 222 222",
    faxinar: true,
    lavar: false,
    passar: false,
    cozinhar: false,
    pagamento: {},
  },
];
